### ISSUE TITLE
import McqView from 'components/adapt-contrib-mcq/js/mcqView'; is wrong written

### ISSUE THREAD

**Issue by clara-am** [adaptlearning/adapt-contrib-gmcq#134]
import McqView from 'components/adapt-contrib-mcq/js/mcqView';
and 
import McqView from 'components/adapt-contrib-mcq/js/mcqModel';

are wrong written. They should be instead (a capital letter is needed):

import McqView from 'components/adapt-contrib-mcq/js/McqView';
import McqView from 'components/adapt-contrib-mcq/js/McqModel';

**Comment by oliverfoster** [comment]
have updated, apologies. please let me know if it doesn't work.
