### ISSUE TITLE
Options read out four times by JAWS

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt-contrib-gmcq#61]
*From @shauncg on October 28, 2014 16:16*

Every GMCQ option is read out multiple times. I think this is as with the MCQs described in cgkineo/adapt_framework#13 - once for the checkbox, once as a heading, and once each for the image title and alt text.

The above refers to Say All (or other Say methods). When tabbing to the options the issue is reduced to about two repetitions.

*Moved from https://github.com/cgkineo/adapt-contrib-gmcq/issues/1*

**Comment by zenduo** [comment]
Hi Tom, is this one still an issue?

**Comment by taylortom** [comment]
Think we closed this on JIRA due to the complete rework of the accessibility stuff. Will see if testing pick this up.
